export const GET_TEAMMATES = 'GET_TEAMMATES';
export const SET_FEEDBACK_TO_USERID = 'SET_FEEDBACK_TO_USERID';
export const GET_FEEDBACK_METRICS = 'GET_FEEDBACK_METRICS';
export const SEND_FEEDBACK = 'SEND_FEEDBACK';
